//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutaDev.CsLib.Gaming.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NutaDev.CsLib.Gaming.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canvas is too small..
        /// </summary>
        public static string CanvasIsTooSmall {
            get {
                return ResourceManager.GetString("CanvasIsTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected type `{0}` but actual is `{1}`..
        /// </summary>
        public static string ExpectedType_0_ButActualIs_1_ {
            get {
                return ResourceManager.GetString("ExpectedType_0_ButActualIs_1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to lock tracker to enumerate achievements..
        /// </summary>
        public static string YouHaveToLockTrackerToEnumerateAchievements {
            get {
                return ResourceManager.GetString("YouHaveToLockTrackerToEnumerateAchievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to lock tracker to enumerate statistics..
        /// </summary>
        public static string YouHaveToLockTrackerToEnumerateStatistics {
            get {
                return ResourceManager.GetString("YouHaveToLockTrackerToEnumerateStatistics", resourceCulture);
            }
        }
    }
}
