//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutaDev.CsLib.Resources.Text.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NutaDev.CsLib.Resources.Text.Exceptions.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `{0}` is not implemented..
        /// </summary>
        public static string _0_IsNotImplemented {
            get {
                return ResourceManager.GetString("_0_IsNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `{0}` is obsolete!.
        /// </summary>
        public static string _0_isObsolete {
            get {
                return ResourceManager.GetString("_0_isObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `{0}` must be greater than zero..
        /// </summary>
        public static string _0_MustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("_0_MustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `{0}` must be smaller than collection size..
        /// </summary>
        public static string _0_MustBeSmallerThanCollectionSize {
            get {
                return ResourceManager.GetString("_0_MustBeSmallerThanCollectionSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `{0}` not found..
        /// </summary>
        public static string _0_NotFound {
            get {
                return ResourceManager.GetString("_0_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occured during deserialization..
        /// </summary>
        public static string AnExceptionOccuredDuringDeserialization {
            get {
                return ResourceManager.GetString("AnExceptionOccuredDuringDeserialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument `{0}` is null..
        /// </summary>
        public static string Argument_0_IsNull {
            get {
                return ResourceManager.GetString("Argument_0_IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument `{0}` is out of range..
        /// </summary>
        public static string Argument_0_IsOutOfRange {
            get {
                return ResourceManager.GetString("Argument_0_IsOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both matrixes must have equal size - `{0}` x `{1}` - and - `{2}` x `{3}`..
        /// </summary>
        public static string BothMatrixesMustHaveEqualSize_0_x_1_And_2_x_3_ {
            get {
                return ResourceManager.GetString("BothMatrixesMustHaveEqualSize_0_x_1_And_2_x_3_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation error `{0}`, Message: `{1}`..
        /// </summary>
        public static string CompilationError_0__1_ {
            get {
                return ResourceManager.GetString("CompilationError_0__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConvertBack, target type `{0}`..
        /// </summary>
        public static string ConvertBackTargetType_0_ {
            get {
                return ResourceManager.GetString("ConvertBackTargetType_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert, target type `{0}`..
        /// </summary>
        public static string ConvertTargetType_0_ {
            get {
                return ResourceManager.GetString("ConvertTargetType_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory `{0}` not found..
        /// </summary>
        public static string Directory_0_NotFound {
            get {
                return ResourceManager.GetString("Directory_0_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate function declaration, name: `{0}`, header: `{1}`..
        /// </summary>
        public static string DuplicateFunctionDeclaration {
            get {
                return ResourceManager.GetString("DuplicateFunctionDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate value `{0}`..
        /// </summary>
        public static string DuplicateValue_0_ {
            get {
                return ResourceManager.GetString("DuplicateValue_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event source is not `{0}`..
        /// </summary>
        public static string EventSourceIsNot_0_ {
            get {
                return ResourceManager.GetString("EventSourceIsNot_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to evaluate expression..
        /// </summary>
        public static string FailedToEvaluateExpression {
            get {
                return ResourceManager.GetString("FailedToEvaluateExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load `{0}` assembly..
        /// </summary>
        public static string FailedToLoad_0_Assembly {
            get {
                return ResourceManager.GetString("FailedToLoad_0_Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open connection..
        /// </summary>
        public static string FailedToOpenConnection {
            get {
                return ResourceManager.GetString("FailedToOpenConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File `{0}` not found..
        /// </summary>
        public static string File_0_NotFound {
            get {
                return ResourceManager.GetString("File_0_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function `{0}` not found..
        /// </summary>
        public static string Function_0_NotFound {
            get {
                return ResourceManager.GetString("Function_0_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High resolution not supported..
        /// </summary>
        public static string HighResolutionNotSupported {
            get {
                return ResourceManager.GetString("HighResolutionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index `{0}` is out of range..
        /// </summary>
        public static string Index_0_IsOutOfRange {
            get {
                return ResourceManager.GetString("Index_0_IsOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index `{0}`, max index: `{1}`..
        /// </summary>
        public static string Index_0_MaxIndex_1 {
            get {
                return ResourceManager.GetString("Index_0_MaxIndex_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character `{0}` at 0-based position `{1}`..
        /// </summary>
        public static string InvalidCharacter_0_At0BasedPosition_1_ {
            get {
                return ResourceManager.GetString("InvalidCharacter_0_At0BasedPosition_1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid offset..
        /// </summary>
        public static string InvalidOffset {
            get {
                return ResourceManager.GetString("InvalidOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token type, expected: `{0}`, was: `{1}`..
        /// </summary>
        public static string InvalidTokenType {
            get {
                return ResourceManager.GetString("InvalidTokenType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token value, expected: `{0}`, was: `{1}`..
        /// </summary>
        public static string InvalidTokenValue {
            get {
                return ResourceManager.GetString("InvalidTokenValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key `{0}` already exists..
        /// </summary>
        public static string Key_0_AlreadyExists {
            get {
                return ResourceManager.GetString("Key_0_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key `{0}` already exists and replacing is not allowed..
        /// </summary>
        public static string Key_0_AlreadyExistsAndReplacingIsNotAllowed {
            get {
                return ResourceManager.GetString("Key_0_AlreadyExistsAndReplacingIsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key `{0}` does not exist..
        /// </summary>
        public static string Key_0_DoesNotExist {
            get {
                return ResourceManager.GetString("Key_0_DoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix `{0}` column count `{1}` must be equal to matrix `{2}` row count `{3}`..
        /// </summary>
        public static string Matrix_0_ColumnCount_1_MustBeEqualToMatrix_2_RowCount_3_ {
            get {
                return ResourceManager.GetString("Matrix_0_ColumnCount_1_MustBeEqualToMatrix_2_RowCount_3_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum is equal to maximum with exclusive flags. Minimum = `{0}`, Maximum = `{1}`, Exclusive maximum =  `{2}`, Exclusive minimum = `{3}`..
        /// </summary>
        public static string MinimumIsEqualToMaximumWithExlusiveFlagsMinimum_0_Maximum_1_ExclusiveMaximum_2_ExclusiveMinimum_3_ {
            get {
                return ResourceManager.GetString("MinimumIsEqualToMaximumWithExlusiveFlagsMinimum_0_Maximum_1_ExclusiveMaximum_2_Ex" +
                        "clusiveMinimum_3_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatched parentheses..
        /// </summary>
        public static string MismatchedParentheses {
            get {
                return ResourceManager.GetString("MismatchedParentheses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misplaced parenthesis or argument separator..
        /// </summary>
        public static string MisplacedParenthesisOrArgumentSeparator {
            get {
                return ResourceManager.GetString("MisplacedParenthesisOrArgumentSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing dice evaluator..
        /// </summary>
        public static string MissingDiceEvaluator {
            get {
                return ResourceManager.GetString("MissingDiceEvaluator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing left operand..
        /// </summary>
        public static string MissingLeftOperand {
            get {
                return ResourceManager.GetString("MissingLeftOperand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing right operand..
        /// </summary>
        public static string MissingRightOperand {
            get {
                return ResourceManager.GetString("MissingRightOperand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing ticks..
        /// </summary>
        public static string MissingTicks {
            get {
                return ResourceManager.GetString("MissingTicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one CUE file in directory `{0}`..
        /// </summary>
        public static string MoreThanOneCueFileInDirectory_0_ {
            get {
                return ResourceManager.GetString("MoreThanOneCueFileInDirectory_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No CUE files in directory `{0}`..
        /// </summary>
        public static string NoCueFilesInDirectory_0_ {
            get {
                return ResourceManager.GetString("NoCueFilesInDirectory_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No discs in CUE file `{0}`..
        /// </summary>
        public static string NoDiscsInCue_0_ {
            get {
                return ResourceManager.GetString("NoDiscsInCue_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No enough space. Got `{0}`, expected `{1}`..
        /// </summary>
        public static string NoEnoughSpaceGot_0_Expected_1_ {
            get {
                return ResourceManager.GetString("NoEnoughSpaceGot_0_Expected_1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more elements in sequence..
        /// </summary>
        public static string NoMoreElementsInSequence {
            get {
                return ResourceManager.GetString("NoMoreElementsInSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No property group found in file `{0}`..
        /// </summary>
        public static string NoPropertyGroupFoundInFile_0_ {
            get {
                return ResourceManager.GetString("NoPropertyGroupFoundInFile_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No target framework for file..
        /// </summary>
        public static string NoTargetFrameworkForFile {
            get {
                return ResourceManager.GetString("NoTargetFrameworkForFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tracks in CUE file `{0}`..
        /// </summary>
        public static string NoTracksInCueFile_0_ {
            get {
                return ResourceManager.GetString("NoTracksInCueFile_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is already disposed..
        /// </summary>
        public static string ObjectIsAlreadyDisposed {
            get {
                return ResourceManager.GetString("ObjectIsAlreadyDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator not supported, type: `{0}`, value: `{1}`..
        /// </summary>
        public static string OperatorNotSupported {
            get {
                return ResourceManager.GetString("OperatorNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service description is required..
        /// </summary>
        public static string ServiceDescriptionIsRequired {
            get {
                return ResourceManager.GetString("ServiceDescriptionIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The `{0}` is not `{1}`..
        /// </summary>
        public static string The_0_IsNot_1_ {
            get {
                return ResourceManager.GetString("The_0_IsNot_1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tried to insert into root node, but node is not a root..
        /// </summary>
        public static string TriedToInserIntoRootNodeButNodeIsNotARoot {
            get {
                return ResourceManager.GetString("TriedToInserIntoRootNodeButNodeIsNotARoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type `{0}` is not an enum..
        /// </summary>
        public static string Type_0_IsNotAnEnum {
            get {
                return ResourceManager.GetString("Type_0_IsNotAnEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown function: `{0}`..
        /// </summary>
        public static string UnknownFunction {
            get {
                return ResourceManager.GetString("UnknownFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t start another task if you haven&apos;t cancelled previous one..
        /// </summary>
        public static string YouCantStartAnotherTaskIfYouHaventCancelledPreviousOne {
            get {
                return ResourceManager.GetString("YouCantStartAnotherTaskIfYouHaventCancelledPreviousOne", resourceCulture);
            }
        }
    }
}
