// The MIT License (MIT)
// 
// Copyright (c) 2022 tariel36
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

using System;
using System.Linq.Expressions;

namespace NutaDev.CsLib.Data.Mappers.Abstract
{
    /// <summary>
    /// Provides set of methods that allows runtime mapping for poco properties.
    /// </summary>
    public interface IPropertyMapper
    {
        /// <summary>
        /// Maps id property.
        /// </summary>
        /// <typeparam name="TType">Object type.</typeparam>
        /// <typeparam name="TReturn">Property type.</typeparam>
        /// <param name="expr">Expression used for mapping.</param>
        /// <param name="isAutoGenerate">Indicates whether propert is autogenerated.</param>
        /// <returns>Reference to self.</returns>
        IPropertyMapper Id<TType, TReturn>(Expression<Func<TType, TReturn>> expr, bool isAutoGenerate);

        /// <summary>
        /// Marks property as ignored.
        /// </summary>
        /// <typeparam name="TType">Object type.</typeparam>
        /// <typeparam name="TReturn">Property type.</typeparam>
        /// <param name="expr">Expression used for mapping.</param>
        /// <returns>Reference to self.</returns>
        IPropertyMapper Ignore<TType, TReturn>(Expression<Func<TType, TReturn>> expr);
    }
}
